apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: danieloh30-poi-backend-app-dev
  annotations:
    argocd/app-name: danieloh30-poi-backend-app-dev
    backstage.io/kubernetes-id: danieloh30-poi-backend-app-dev
    backstage.io/kubernetes-namespace: danieloh30
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=danieloh30-poi-backend-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/danieloh30-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/danieloh30/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/danieloh30/deployments/danieloh30-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/danieloh30-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/danieloh30"
  system: workshop-system-danieloh30
  providesApis:
    - backend-api-danieloh30
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-danieloh30
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/danieloh30"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-danieloh30
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://danieloh30-poi-backend-app-danieloh30.apps.rosa916.9nln.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rosa916-rvhvd/danieloh30-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/danieloh30"
  system: workshop-system-danieloh30
  definition:
    $text: https://github.com/rosa916-rvhvd/danieloh30-backend/tree/main/src/main/resources/META-INF/openapi.yaml
